# Generated by Django 6.0.7 on 2026-07-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_center", "0002_futureupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendEmailToAll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Send Email To All",
                "verbose_name_plural": "Send Email To All",
                "managed": False,
            },
        ),
    ]
