# Generated by Django 6.0.7 on 2026-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="type",
            field=models.CharField(
                choices=[
                    ("mountain", "Mountains"),
                    ("forest", "Forest"),
                    ("river", "River"),
                    ("lake", "Lake"),
                    ("ocean", "Ocean"),
                    ("desert", "Desert"),
                    ("city", "City"),
                    ("town", "Town"),
                    ("village", "Village"),
                    ("countryside", "Countryside"),
                    ("beach", "Beach"),
                    ("island", "Island"),
                    ("waterfall", "Waterfall"),
                    ("canyon", "Canyon"),
                    ("cave", "Cave"),
                    ("volcano", "Volcano"),
                    ("glacier", "Glacier"),
                    ("park", "Park"),
                    ("garden", "Garden"),
                    ("zoo", "Zoo"),
                    ("museum", "Museum"),
                    ("gallery", "Gallery"),
                    ("monument", "Monument"),
                    ("historical", "Historical"),
                    ("religious", "Religious"),
                    ("cultural", "Cultural"),
                    ("traditional", "Traditional"),
                    ("modern", "Modern"),
                    ("architectural", "Architectural"),
                    ("natural", "Natural"),
                    ("artificial", "Artificial"),
                    ("commercial", "Commercial"),
                    ("industrial", "Industrial"),
                    ("residential", "Residential"),
                    ("agricultural", "Agricultural"),
                    ("wildlife", "Wildlife"),
                    ("bird", "Bird"),
                    ("animal", "Animal"),
                    ("plant", "Plant"),
                    ("flower", "Flower"),
                    ("tree", "Tree"),
                ],
                max_length=100,
            ),
        ),
    ]
