# Generated by Django 6.0.7 on 2026-07-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_gallery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(max_length=500, upload_to="gallery/images/"),
        ),
    ]
