# Generated by Django 6.0.7 on 2026-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("General Inquiry", "General Inquiry"),
                            ("Booking Questions", "Booking Questions"),
                            ("Payment Issues", "Payment Issues"),
                            ("Custom Itinerary Request", "Custom Itinerary Request"),
                            ("Feedback", "Feedback"),
                            ("Partnership Opportunities", "Partnership Opportunities"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(max_length=500)),
            ],
        ),
    ]
