# Generated by Django 6.0.7 on 2026-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                help_text="Enter your email address", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="full_name",
            field=models.CharField(help_text="Enter your full name", max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(help_text="Enter your message", max_length=500),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(
                choices=[
                    ("General Inquiry", "General Inquiry"),
                    ("Booking Questions", "Booking Questions"),
                    ("Payment Issues", "Payment Issues"),
                    ("Custom Itinerary Request", "Custom Itinerary Request"),
                    ("Feedback", "Feedback"),
                    ("Partnership Opportunities", "Partnership Opportunities"),
                    ("Other", "Other"),
                ],
                help_text="Select the subject of your inquiry",
                max_length=100,
            ),
        ),
    ]
