# Generated by Django 6.0.7 on 2026-07-14 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contact_email_alter_contact_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 7, 14, 8, 45, 59, 615234, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
