# Generated by Django 6.0.7 on 2026-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="address",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
