# Generated by Django 6.0.7 on 2026-07-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_profile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="profile_pics"
            ),
        ),
    ]
