# Generated by Django 6.0.7 on 2026-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packages",
            name="tag_line",
            field=models.CharField(
                choices=[
                    ("Adventure", "Adventure"),
                    ("Relaxation", "Relaxation"),
                    ("Cultural", "Cultural"),
                    ("Romantic", "Romantic"),
                    ("Family", "Family"),
                    ("Luxury", "Luxury"),
                    ("Budget", "Budget"),
                    ("Best Seller", "Best Seller"),
                    ("None", "None"),
                ],
                default="None",
                max_length=100,
            ),
        ),
    ]
