# Generated by Django 6.0.7 on 2026-07-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_alter_packages_tag_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="packages_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="packages.packages",
                    ),
                ),
            ],
        ),
    ]
