# Generated by Django 6.0.7 on 2026-07-15 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_packagesdeparturedate_packagesfeatures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packages",
            name="category",
            field=models.CharField(
                choices=[
                    ("Beach", "Beach"),
                    ("Adventure", "Adventure"),
                    ("Culture", "Culture"),
                    ("Diving", "Diving"),
                ],
                default=django.utils.timezone.now,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
