# Generated by Django 6.0.7 on 2026-07-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0005_packages_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagesimage",
            name="image",
            field=models.ImageField(max_length=500, upload_to="packages_images/"),
        ),
    ]
